server:
  applicationConnectors:
    - type: http
      port: 22000

  adminConnectors:
    - type: http
      port: 22001

logging:
  level: INFO
  loggers:
    com.cleo.data.transform: DEBUG

# Database settings.
# the name of the JDBC driver, mysql in our case
driverClass: com.mysql.jdbc.Driver
# the username
user: root
# the password
password: root
# the JDBC URL; the database is called cleo
url: jdbc:mysql://localhost:3306/cleo
